"use client"

import type React from "react"
import { createContext, useContext, useState, useEffect } from "react"

type Language = "en" | "es" | "fr" | "de" | "it" | "pt" | "ru" | "zh" | "ja" | "ko" | "hi"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const translations = {
  en: {
    // Navigation
    dashboard: "Dashboard",
    pomodoro: "Pomodoro Timer",
    tasks: "Tasks",
    timetable: "Timetable",
    habits: "Habits",
    goals: "Goals",
    budget: "Budget",
    study: "Study",
    medications: "Medications",
    reminders: "Reminders",
    analytics: "Analytics",
    settings: "Settings",
    health: "Health Tracker",
    studyFlow: "StudyFlow",

    // Common
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    add: "Add",
    complete: "Complete",
    start: "Start",
    stop: "Stop",
    pause: "Pause",
    resume: "Resume",
    reset: "Reset",
    saveChanges: "Save Changes",
    resetToDefaults: "Reset to Defaults",

    // Dashboard
    welcomeBack: "Welcome back! Here's an overview of your productivity.",
    overview: "Overview",
    schedule: "Schedule",
    pendingTasks: "Pending Tasks",
    upcomingEvents: "Upcoming Events",
    weeklyProgress: "Weekly Progress",
    studyTimeToday: "Study Time Today",
    minutesToGoal: "minutes to daily goal",
    highPriority: "high priority",
    upcomingTasks: "Upcoming Tasks",
    pendingAssignments: "Your pending assignments and tasks",
    todaySchedule: "Today's Schedule",
    eventsAndClasses: "Your events and classes for today",
    aiSuggestions: "AI Suggestions",
    smartRecommendations: "Smart recommendations based on your current activity",
    greatJob: "Great job! You have 1 habit with strong streaks. Keep it up!",
    viewProgress: "View Progress",

    // Health Tracker
    steps: "Steps",
    water: "Water Intake",
    sleep: "Sleep",
    weight: "Weight",
    heartRate: "Heart Rate",
    calories: "Calories",
    exercise: "Exercise",
    todaySteps: "Today's Steps",
    waterGoal: "Water Goal",
    sleepHours: "Sleep Hours",
    currentWeight: "Current Weight",
    distance: "Distance",
    autoTracking: "Auto Tracking",
    manualEntry: "Manual Entry",

    // Settings
    profile: "Profile",
    preferences: "Preferences",
    notifications: "Notifications",
    privacy: "Privacy",
    language: "Language",
    theme: "Theme",
    currency: "Currency",
    enableNotifications: "Enable Notifications",
    profileInformation: "Profile Information",
    updatePersonalInfo: "Update your personal information",
    appearance: "Appearance",
    customizeApp: "Customize how the app looks and feels",
    notificationSettings: "Notification Settings",
    manageNotifications: "Manage how you receive notifications",
    privacySettings: "Privacy Settings",
    managePrivacy: "Manage your privacy preferences",
    pushNotifications: "Push Notifications",
    receiveNotifications: "Receive notifications on your device",
    emailNotifications: "Email Notifications",
    receiveEmail: "Receive notifications via email",
    soundNotifications: "Sound Notifications",
    playSound: "Play sound with notifications",
    showOnlineStatus: "Show Online Status",
    allowOnline: "Allow others to see when you're online",
    shareActivity: "Share Activity Statistics",
    shareStats: "Share your activity statistics with friends",
    allowDataCollection: "Allow Data Collection",
    collectData: "Allow us to collect anonymous usage data to improve the app",
    notificationsEnabled: "Notifications Enabled",
    notificationsDisabled: "Notifications Disabled",
    willReceiveNotifications: "You will receive notifications for reminders, tasks, and important updates.",
    enableToReceive: "Enable notifications to receive important reminders and updates.",
    sendTestNotification: "Send Test Notification",
    enableNotificationsNow: "Enable Notifications Now",
    changeAvatar: "Change Avatar",
    name: "Name",
    email: "Email",
    light: "Light",
    dark: "Dark",
    system: "System",
    timeFormat: "Time Format",
    selectTimeFormat: "Select time format",
    selectCurrency: "Select currency",
    voiceInput: "Voice Input",
    enableVoiceInput: "Enable voice input for text fields",
    soundEffects: "Sound Effects",
    enableSoundEffects: "Enable sound effects for notifications and actions",

    // Notifications
    pomodoroComplete: "Pomodoro session completed! Time for a break.",
    medicationReminder: "Time to take your medication",
    taskDue: "Task is due soon",
    habitReminder: "Don't forget your habit",
    goalDeadline: "Goal deadline approaching",
    testNotification: "Test Notification",
    testNotificationBody: "This is a test notification to confirm they're working properly.",
  },
  hi: {
    // Navigation
    dashboard: "डैशबोर्ड",
    pomodoro: "पोमोडोरो टाइमर",
    tasks: "कार्य",
    timetable: "समय सारणी",
    habits: "आदतें",
    goals: "लक्ष्य",
    budget: "बजट",
    study: "अध्ययन",
    medications: "दवाइयां",
    reminders: "अनुस्मारक",
    analytics: "विश्लेषण",
    settings: "सेटिंग्स",
    health: "स्वास्थ्य ट्रैकर",
    studyFlow: "स्टडीफ्लो",

    // Common
    save: "सेव करें",
    cancel: "रद्द करें",
    delete: "हटाएं",
    edit: "संपादित करें",
    add: "जोड़ें",
    complete: "पूरा करें",
    start: "शुरू करें",
    stop: "रोकें",
    pause: "रोकें",
    resume: "फिर से शुरू करें",
    reset: "रीसेट करें",
    saveChanges: "परिवर्तन सेव करें",
    resetToDefaults: "डिफ़ॉल्ट पर रीसेट करें",

    // Dashboard
    welcomeBack: "वापसी पर स्वागत है! यहां आपकी उत्पादकता का अवलोकन है।",
    overview: "अवलोकन",
    schedule: "अनुसूची",
    pendingTasks: "लंबित कार्य",
    upcomingEvents: "आगामी कार्यक्रम",
    weeklyProgress: "साप्ताहिक प्रगति",
    studyTimeToday: "आज का अध्ययन समय",
    minutesToGoal: "दैनिक लक्ष्य तक मिनट",
    highPriority: "उच्च प्राथमिकता",
    upcomingTasks: "आगामी कार्य",
    pendingAssignments: "आपके लंबित असाइनमेंट और कार्य",
    todaySchedule: "आज की अनुसूची",
    eventsAndClasses: "आज के लिए आपके कार्यक्रम और कक्षाएं",
    aiSuggestions: "एआई सुझाव",
    smartRecommendations: "आपकी वर्तमान गतिविधि के आधार पर स्मार्ट सिफारिशें",
    greatJob: "शानदार काम! आपकी 1 आदत में मजबूत स्ट्रीक है। इसे जारी रखें!",
    viewProgress: "प्रगति देखें",

    // Health Tracker
    steps: "कदम",
    water: "पानी का सेवन",
    sleep: "नींद",
    weight: "वजन",
    heartRate: "हृदय गति",
    calories: "कैलोरी",
    exercise: "व्यायाम",
    todaySteps: "आज के कदम",
    waterGoal: "पानी का लक्ष्य",
    sleepHours: "नींद के घंटे",
    currentWeight: "वर्तमान वजन",
    distance: "दूरी",
    autoTracking: "ऑटो ट्रैकिंग",
    manualEntry: "मैन्युअल एंट्री",

    // Settings
    profile: "प्रोफाइल",
    preferences: "प्राथमिकताएं",
    notifications: "सूचनाएं",
    privacy: "गोपनीयता",
    language: "भाषा",
    theme: "थीम",
    currency: "मुद्रा",
    enableNotifications: "सूचनाएं सक्षम करें",
    profileInformation: "प्रोफाइल जानकारी",
    updatePersonalInfo: "अपनी व्यक्तिगत जानकारी अपडेट करें",
    appearance: "दिखावट",
    customizeApp: "ऐप के दिखने और महसूस होने के तरीके को अनुकूलित करें",
    notificationSettings: "सूचना सेटिंग्स",
    manageNotifications: "सूचनाएं प्राप्त करने के तरीके का प्रबंधन करें",
    privacySettings: "गोपनीयता सेटिंग्स",
    managePrivacy: "अपनी गोपनीयता प्राथमिकताओं का प्रबंधन करें",
    pushNotifications: "पुश सूचनाएं",
    receiveNotifications: "अपने डिवाइस पर सूचनाएं प्राप्त करें",
    emailNotifications: "ईमेल सूचनाएं",
    receiveEmail: "ईमेल के माध्यम से सूचनाएं प्राप्त करें",
    soundNotifications: "ध्वनि सूचनाएं",
    playSound: "सूचनाओं के साथ ध्वनि बजाएं",
    showOnlineStatus: "ऑनलाइन स्थिति दिखाएं",
    allowOnline: "दूसरों को देखने दें कि आप कब ऑनलाइन हैं",
    shareActivity: "गतिविधि आंकड़े साझा करें",
    shareStats: "अपने गतिविधि आंकड़े दोस्तों के साथ साझा करें",
    allowDataCollection: "डेटा संग्रह की अनुमति दें",
    collectData: "ऐप को बेहतर बनाने के लिए अनाम उपयोग डेटा एकत्र करने की अनुमति दें",
    notificationsEnabled: "सूचनाएं सक्षम हैं",
    notificationsDisabled: "सूचनाएं अक्षम हैं",
    willReceiveNotifications: "आपको अनुस्मारक, कार्यों और महत्वपूर्ण अपडेट के लिए सूचनाएं मिलेंगी।",
    enableToReceive: "महत्वपूर्ण अनुस्मारक और अपडेट प्राप्त करने के लिए सूचनाएं सक्षम करें।",
    sendTestNotification: "परीक्षण सूचना भेजें",
    enableNotificationsNow: "अभी सूचनाएं सक्षम करें",
    changeAvatar: "अवतार बदलें",
    name: "नाम",
    email: "ईमेल",
    light: "लाइट",
    dark: "डार्क",
    system: "सिस्टम",
    timeFormat: "समय प्रारूप",
    selectTimeFormat: "समय प्रारूप चुनें",
    selectCurrency: "मुद्रा चुनें",
    voiceInput: "वॉइस इनपुट",
    enableVoiceInput: "टेक्स्ट फील्ड के लिए वॉइस इनपुट सक्षम करें",
    soundEffects: "ध्वनि प्रभाव",
    enableSoundEffects: "सूचनाओं और क्रियाओं के लिए ध्वनि प्रभाव सक्षम करें",

    // Notifications
    pomodoroComplete: "पोमोडोरो सत्र पूरा हुआ! आराम का समय।",
    medicationReminder: "दवा लेने का समय",
    taskDue: "कार्य जल्द ही समाप्त होने वाला है",
    habitReminder: "अपनी आदत मत भूलिए",
    goalDeadline: "लक्ष्य की समय सीमा नजदीक आ रही है",
    testNotification: "परीक्षण सूचना",
    testNotificationBody: "यह एक परीक्षण सूचना है जो पुष्टि करती है कि वे ठीक से काम कर रही हैं।",
  },
  es: {
    // Navigation
    dashboard: "Panel de Control",
    pomodoro: "Temporizador Pomodoro",
    tasks: "Tareas",
    timetable: "Horario",
    habits: "Hábitos",
    goals: "Objetivos",
    budget: "Presupuesto",
    study: "Estudio",
    medications: "Medicamentos",
    reminders: "Recordatorios",
    analytics: "Análisis",
    settings: "Configuración",
    health: "Monitor de Salud",
    studyFlow: "StudyFlow",

    // Common
    save: "Guardar",
    cancel: "Cancelar",
    delete: "Eliminar",
    edit: "Editar",
    add: "Agregar",
    complete: "Completar",
    start: "Iniciar",
    stop: "Detener",
    pause: "Pausar",
    resume: "Reanudar",
    reset: "Reiniciar",
    saveChanges: "Guardar Cambios",
    resetToDefaults: "Restablecer a Predeterminados",

    // Health Tracker
    steps: "Pasos",
    water: "Consumo de Agua",
    sleep: "Sueño",
    weight: "Peso",
    heartRate: "Ritmo Cardíaco",
    calories: "Calorías",
    exercise: "Ejercicio",
    todaySteps: "Pasos de Hoy",
    waterGoal: "Meta de Agua",
    sleepHours: "Horas de Sueño",
    currentWeight: "Peso Actual",
    distance: "Distancia",
    autoTracking: "Seguimiento Automático",
    manualEntry: "Entrada Manual",

    // Settings
    profile: "Perfil",
    preferences: "Preferencias",
    notifications: "Notificaciones",
    privacy: "Privacidad",
    language: "Idioma",
    theme: "Tema",
    currency: "Moneda",
    enableNotifications: "Habilitar Notificaciones",

    // Notifications
    pomodoroComplete: "¡Sesión Pomodoro completada! Hora de un descanso.",
    medicationReminder: "Hora de tomar tu medicamento",
    taskDue: "La tarea vence pronto",
    habitReminder: "No olvides tu hábito",
    goalDeadline: "Se acerca la fecha límite del objetivo",
  },
  fr: {
    // Navigation
    dashboard: "Tableau de Bord",
    pomodoro: "Minuteur Pomodoro",
    tasks: "Tâches",
    timetable: "Emploi du Temps",
    habits: "Habitudes",
    goals: "Objectifs",
    budget: "Budget",
    study: "Étude",
    medications: "Médicaments",
    reminders: "Rappels",
    analytics: "Analyses",
    settings: "Paramètres",
    health: "Suivi Santé",
    studyFlow: "StudyFlow",

    // Common
    save: "Sauvegarder",
    cancel: "Annuler",
    delete: "Supprimer",
    edit: "Modifier",
    add: "Ajouter",
    complete: "Terminer",
    start: "Commencer",
    stop: "Arrêter",
    pause: "Pause",
    resume: "Reprendre",
    reset: "Réinitialiser",
    saveChanges: "Sauvegarder les Modifications",
    resetToDefaults: "Réinitialiser aux Paramètres par Défaut",

    // Health Tracker
    steps: "Pas",
    water: "Consommation d'Eau",
    sleep: "Sommeil",
    weight: "Poids",
    heartRate: "Rythme Cardiaque",
    calories: "Calories",
    exercise: "Exercice",
    todaySteps: "Pas d'Aujourd'hui",
    waterGoal: "Objectif d'Eau",
    sleepHours: "Heures de Sommeil",
    currentWeight: "Poids Actuel",
    distance: "Distance",
    autoTracking: "Suivi Automatique",
    manualEntry: "Saisie Manuelle",

    // Settings
    profile: "Profil",
    preferences: "Préférences",
    notifications: "Notifications",
    privacy: "Confidentialité",
    language: "Langue",
    theme: "Thème",
    currency: "Devise",
    enableNotifications: "Activer les Notifications",

    // Notifications
    pomodoroComplete: "Session Pomodoro terminée ! Temps pour une pause.",
    medicationReminder: "Il est temps de prendre vos médicaments",
    taskDue: "La tâche est bientôt due",
    habitReminder: "N'oubliez pas votre habitude",
    goalDeadline: "Date limite de l'objectif approche",
  },
  de: {
    // Navigation
    dashboard: "Dashboard",
    pomodoro: "Pomodoro Timer",
    tasks: "Aufgaben",
    timetable: "Stundenplan",
    habits: "Gewohnheiten",
    goals: "Ziele",
    budget: "Budget",
    study: "Studium",
    medications: "Medikamente",
    reminders: "Erinnerungen",
    analytics: "Analysen",
    settings: "Einstellungen",
    health: "Gesundheits-Tracker",
    studyFlow: "StudyFlow",

    // Common
    save: "Speichern",
    cancel: "Abbrechen",
    delete: "Löschen",
    edit: "Bearbeiten",
    add: "Hinzufügen",
    complete: "Abschließen",
    start: "Starten",
    stop: "Stoppen",
    pause: "Pausieren",
    resume: "Fortsetzen",
    reset: "Zurücksetzen",
    saveChanges: "Änderungen Speichern",
    resetToDefaults: "Auf Standardeinstellungen Zurücksetzen",

    // Health Tracker
    steps: "Schritte",
    water: "Wasseraufnahme",
    sleep: "Schlaf",
    weight: "Gewicht",
    heartRate: "Herzfrequenz",
    calories: "Kalorien",
    exercise: "Übung",
    todaySteps: "Heutige Schritte",
    waterGoal: "Wasserziel",
    sleepHours: "Schlafstunden",
    currentWeight: "Aktuelles Gewicht",
    distance: "Entfernung",
    autoTracking: "Automatische Verfolgung",
    manualEntry: "Manuelle Eingabe",

    // Settings
    profile: "Profil",
    preferences: "Einstellungen",
    notifications: "Benachrichtigungen",
    privacy: "Datenschutz",
    language: "Sprache",
    theme: "Design",
    currency: "Währung",
    enableNotifications: "Benachrichtigungen Aktivieren",

    // Notifications
    pomodoroComplete: "Pomodoro-Sitzung abgeschlossen! Zeit für eine Pause.",
    medicationReminder: "Zeit, Ihre Medikamente zu nehmen",
    taskDue: "Aufgabe ist bald fällig",
    habitReminder: "Vergessen Sie Ihre Gewohnheit nicht",
    goalDeadline: "Zieltermin nähert sich",
  },
  it: {
    // Navigation
    dashboard: "Cruscotto",
    pomodoro: "Timer Pomodoro",
    tasks: "Compiti",
    timetable: "Orario",
    habits: "Abitudini",
    goals: "Obiettivi",
    budget: "Budget",
    study: "Studio",
    medications: "Farmaci",
    reminders: "Promemoria",
    analytics: "Analisi",
    settings: "Impostazioni",
    health: "Tracker Salute",
    studyFlow: "StudyFlow",

    // Common
    save: "Salva",
    cancel: "Annulla",
    delete: "Elimina",
    edit: "Modifica",
    add: "Aggiungi",
    complete: "Completa",
    start: "Inizia",
    stop: "Ferma",
    pause: "Pausa",
    resume: "Riprendi",
    reset: "Reimposta",
    saveChanges: "Salva Modifiche",
    resetToDefaults: "Ripristina Impostazioni Predefinite",

    // Health Tracker
    steps: "Passi",
    water: "Assunzione Acqua",
    sleep: "Sonno",
    weight: "Peso",
    heartRate: "Frequenza Cardiaca",
    calories: "Calorie",
    exercise: "Esercizio",
    todaySteps: "Passi di Oggi",
    waterGoal: "Obiettivo Acqua",
    sleepHours: "Ore di Sonno",
    currentWeight: "Peso Attuale",
    distance: "Distanza",
    autoTracking: "Tracciamento Automatico",
    manualEntry: "Inserimento Manuale",

    // Settings
    profile: "Profilo",
    preferences: "Preferenze",
    notifications: "Notifiche",
    privacy: "Privacy",
    language: "Lingua",
    theme: "Tema",
    currency: "Valuta",
    enableNotifications: "Abilita Notifiche",

    // Notifications
    pomodoroComplete: "Sessione Pomodoro completata! Tempo per una pausa.",
    medicationReminder: "È ora di prendere i farmaci",
    taskDue: "Il compito scade presto",
    habitReminder: "Non dimenticare la tua abitudine",
    goalDeadline: "Scadenza obiettivo in avvicinamento",
  },
  pt: {
    // Navigation
    dashboard: "Painel",
    pomodoro: "Timer Pomodoro",
    tasks: "Tarefas",
    timetable: "Horário",
    habits: "Hábitos",
    goals: "Objetivos",
    budget: "Orçamento",
    study: "Estudo",
    medications: "Medicamentos",
    reminders: "Lembretes",
    analytics: "Análises",
    settings: "Configurações",
    health: "Monitor de Saúde",
    studyFlow: "StudyFlow",

    // Common
    save: "Salvar",
    cancel: "Cancelar",
    delete: "Excluir",
    edit: "Editar",
    add: "Adicionar",
    complete: "Completar",
    start: "Iniciar",
    stop: "Parar",
    pause: "Pausar",
    resume: "Retomar",
    reset: "Reiniciar",
    saveChanges: "Salvar Alterações",
    resetToDefaults: "Redefinir para Padrões",

    // Health Tracker
    steps: "Passos",
    water: "Consumo de Água",
    sleep: "Sono",
    weight: "Peso",
    heartRate: "Frequência Cardíaca",
    calories: "Calorias",
    exercise: "Exercício",
    todaySteps: "Passos de Hoje",
    waterGoal: "Meta de Água",
    sleepHours: "Horas de Sono",
    currentWeight: "Peso Atual",
    distance: "Distância",
    autoTracking: "Rastreamento Automático",
    manualEntry: "Entrada Manual",

    // Settings
    profile: "Perfil",
    preferences: "Preferências",
    notifications: "Notificações",
    privacy: "Privacidade",
    language: "Idioma",
    theme: "Tema",
    currency: "Moeda",
    enableNotifications: "Ativar Notificações",

    // Notifications
    pomodoroComplete: "Sessão Pomodoro concluída! Hora de uma pausa.",
    medicationReminder: "Hora de tomar seus medicamentos",
    taskDue: "Tarefa vence em breve",
    habitReminder: "Não esqueça seu hábito",
    goalDeadline: "Prazo do objetivo se aproximando",
  },
  ru: {
    // Navigation
    dashboard: "Панель управления",
    pomodoro: "Таймер Помодоро",
    tasks: "Задачи",
    timetable: "Расписание",
    habits: "Привычки",
    goals: "Цели",
    budget: "Бюджет",
    study: "Учеба",
    medications: "Лекарства",
    reminders: "Напоминания",
    analytics: "Аналитика",
    settings: "Настройки",
    health: "Трекер здоровья",
    studyFlow: "StudyFlow",

    // Common
    save: "Сохранить",
    cancel: "Отмена",
    delete: "Удалить",
    edit: "Редактировать",
    add: "Добавить",
    complete: "Завершить",
    start: "Начать",
    stop: "Остановить",
    pause: "Пауза",
    resume: "Продолжить",
    reset: "Сбросить",
    saveChanges: "Сохранить Изменения",
    resetToDefaults: "Сбросить к Настройкам по Умолчанию",

    // Health Tracker
    steps: "Шаги",
    water: "Потребление воды",
    sleep: "Сон",
    weight: "Вес",
    heartRate: "Пульс",
    calories: "Калории",
    exercise: "Упражнения",
    todaySteps: "Шаги сегодня",
    waterGoal: "Цель по воде",
    sleepHours: "Часы сна",
    currentWeight: "Текущий вес",
    distance: "Расстояние",
    autoTracking: "Автоматическое Отслеживание",
    manualEntry: "Ручной Ввод",

    // Settings
    profile: "Профиль",
    preferences: "Предпочтения",
    notifications: "Уведомления",
    privacy: "Конфиденциальность",
    language: "Язык",
    theme: "Тема",
    currency: "Валюта",
    enableNotifications: "Включить Уведомления",

    // Notifications
    pomodoroComplete: "Сессия Помодоро завершена! Время для перерыва.",
    medicationReminder: "Время принимать лекарства",
    taskDue: "Задача скоро истекает",
    habitReminder: "Не забудьте о своей привычке",
    goalDeadline: "Приближается срок цели",
  },
  zh: {
    // Navigation
    dashboard: "仪表板",
    pomodoro: "番茄钟",
    tasks: "任务",
    timetable: "时间表",
    habits: "习惯",
    goals: "目标",
    budget: "预算",
    study: "学习",
    medications: "药物",
    reminders: "提醒",
    analytics: "分析",
    settings: "设置",
    health: "健康追踪",
    studyFlow: "StudyFlow",

    // Common
    save: "保存",
    cancel: "取消",
    delete: "删除",
    edit: "编辑",
    add: "添加",
    complete: "完成",
    start: "开始",
    stop: "停止",
    pause: "暂停",
    resume: "继续",
    reset: "重置",
    saveChanges: "保存更改",
    resetToDefaults: "重置为默认值",

    // Health Tracker
    steps: "步数",
    water: "饮水量",
    sleep: "睡眠",
    weight: "体重",
    heartRate: "心率",
    calories: "卡路里",
    exercise: "运动",
    todaySteps: "今日步数",
    waterGoal: "饮水目标",
    sleepHours: "睡眠时间",
    currentWeight: "当前体重",
    distance: "距离",
    autoTracking: "自动追踪",
    manualEntry: "手动输入",

    // Settings
    profile: "个人资料",
    preferences: "偏好设置",
    notifications: "通知",
    privacy: "隐私",
    language: "语言",
    theme: "主题",
    currency: "货币",
    enableNotifications: "启用通知",

    // Notifications
    pomodoroComplete: "番茄钟完成！休息时间到了。",
    medicationReminder: "该吃药了",
    taskDue: "任务即将到期",
    habitReminder: "别忘了你的习惯",
    goalDeadline: "目标截止日期临近",
  },
  ja: {
    // Navigation
    dashboard: "ダッシュボード",
    pomodoro: "ポモドーロタイマー",
    tasks: "タスク",
    timetable: "時間割",
    habits: "習慣",
    goals: "目標",
    budget: "予算",
    study: "勉強",
    medications: "薬",
    reminders: "リマインダー",
    analytics: "分析",
    settings: "設定",
    health: "健康トラッカー",
    studyFlow: "StudyFlow",

    // Common
    save: "保存",
    cancel: "キャンセル",
    delete: "削除",
    edit: "編集",
    add: "追加",
    complete: "完了",
    start: "開始",
    stop: "停止",
    pause: "一時停止",
    resume: "再開",
    reset: "リセット",
    saveChanges: "変更を保存",
    resetToDefaults: "デフォルトにリセット",

    // Health Tracker
    steps: "歩数",
    water: "水分摂取",
    sleep: "睡眠",
    weight: "体重",
    heartRate: "心拍数",
    calories: "カロリー",
    exercise: "運動",
    todaySteps: "今日の歩数",
    waterGoal: "水分目標",
    sleepHours: "睡眠時間",
    currentWeight: "現在の体重",
    distance: "距離",
    autoTracking: "自動追跡",
    manualEntry: "手動入力",

    // Settings
    profile: "プロフィール",
    preferences: "設定",
    notifications: "通知",
    privacy: "プライバシー",
    language: "言語",
    theme: "テーマ",
    currency: "通貨",
    enableNotifications: "通知を有効にする",

    // Notifications
    pomodoroComplete: "ポモドーロセッション完了！休憩時間です。",
    medicationReminder: "薬を飲む時間です",
    taskDue: "タスクの期限が近づいています",
    habitReminder: "習慣を忘れずに",
    goalDeadline: "目標の締切が近づいています",
  },
  ko: {
    // Navigation
    dashboard: "대시보드",
    pomodoro: "포모도로 타이머",
    tasks: "작업",
    timetable: "시간표",
    habits: "습관",
    goals: "목표",
    budget: "예산",
    study: "공부",
    medications: "약물",
    reminders: "알림",
    analytics: "분석",
    settings: "설정",
    health: "건강 추적기",
    studyFlow: "StudyFlow",

    // Common
    save: "저장",
    cancel: "취소",
    delete: "삭제",
    edit: "편집",
    add: "추가",
    complete: "완료",
    start: "시작",
    stop: "중지",
    pause: "일시정지",
    resume: "재개",
    reset: "재설정",
    saveChanges: "변경사항 저장",
    resetToDefaults: "기본값으로 재설정",

    // Health Tracker
    steps: "걸음수",
    water: "수분 섭취",
    sleep: "수면",
    weight: "체중",
    heartRate: "심박수",
    calories: "칼로리",
    exercise: "운동",
    todaySteps: "오늘의 걸음수",
    waterGoal: "수분 목표",
    sleepHours: "수면 시간",
    currentWeight: "현재 체중",
    distance: "거리",
    autoTracking: "자동 추적",
    manualEntry: "수동 입력",

    // Settings
    profile: "프로필",
    preferences: "환경설정",
    notifications: "알림",
    privacy: "개인정보",
    language: "언어",
    theme: "테마",
    currency: "통화",
    enableNotifications: "알림 활성화",

    // Notifications
    pomodoroComplete: "포모도로 세션 완료! 휴식 시간입니다.",
    medicationReminder: "약 복용 시간입니다",
    taskDue: "작업 마감일이 다가옵니다",
    habitReminder: "습관을 잊지 마세요",
    goalDeadline: "목표 마감일이 다가옵니다",
  },
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("en")

  useEffect(() => {
    const savedLanguage = localStorage.getItem("app-language") as Language
    if (savedLanguage && translations[savedLanguage]) {
      setLanguage(savedLanguage)
    }
  }, [])

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang)
    localStorage.setItem("app-language", lang)
  }

  const t = (key: string): string => {
    return translations[language][key as keyof (typeof translations)[typeof language]] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
